import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

export interface VolcanoItem {
  id: string
  nama: string
  kode: string
  lat: number
  lng: number
  elevation: number // mdpl
  provinsi: string
  kabupaten: string
  level: 1 | 2 | 3 | 4
  status: string
  statusColor: string
  hazardRadiusKm: number
  rekomendasi: string
  link: string
  updatedAt?: string
}

// Master catalogue of active volcanoes in Indonesia monitored by PVMBG (MAGMA ESDM)
const MASTER_VOLCANOES: VolcanoItem[] = [
  // ── Level III (Siaga) / Active High Concern ──
  {
    id: 'merapi',
    nama: 'Gunung Merapi',
    kode: 'MER',
    lat: -7.5407,
    lng: 110.4457,
    elevation: 2968,
    provinsi: 'DI Yogyakarta & Jawa Tengah',
    kabupaten: 'Sleman, Magelang, Boyolali, Klaten',
    level: 3,
    status: 'Level III (Siaga)',
    statusColor: '#ea580c',
    hazardRadiusKm: 7.0,
    rekomendasi: 'Masyarakat agar tidak melakukan kegiatan apapun di daerah potensi bahaya. Potensi guguran lava dan awanpanas pada sektor selatan-barat daya meliputi Sungai Boyong sejauh maks 5 km, Bedog, Krasak, Bebeng sejauh maks 7 km.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'semeru',
    nama: 'Gunung Semeru',
    kode: 'SMR',
    lat: -8.108,
    lng: 112.922,
    elevation: 3676,
    provinsi: 'Jawa Timur',
    kabupaten: 'Lumajang, Malang',
    level: 3,
    status: 'Level III (Siaga)',
    statusColor: '#ea580c',
    hazardRadiusKm: 5.0,
    rekomendasi: 'Tidak melakukan aktivitas apapun di sektor tenggara di sepanjang Besuk Kobokan, sejauh 13 km dari puncak (pusat erupsi). Di luar jarak tersebut, tidak melakukan aktivitas pada jarak 500 meter dari tepi sungai sepanjang Besuk Kobokan.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'lewotobi-laki-laki',
    nama: 'Gunung Lewotobi Laki-laki',
    kode: 'LWK',
    lat: -8.5389,
    lng: 122.7686,
    elevation: 1584,
    provinsi: 'Nusa Tenggara Timur',
    kabupaten: 'Flores Timur',
    level: 3,
    status: 'Level III (Siaga)',
    statusColor: '#ea580c',
    hazardRadiusKm: 6.0,
    rekomendasi: 'Masyarakat dan wisatawan di sekitar G. Lewotobi Laki-laki tidak melakukan aktivitas apapun dalam radius 6 km dari pusat erupsi serta sektoral barat daya-timur laut sejauh 7 km.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'marapi',
    nama: 'Gunung Marapi',
    kode: 'MAR',
    lat: -0.381,
    lng: 100.473,
    elevation: 2891,
    provinsi: 'Sumatera Barat',
    kabupaten: 'Agam, Tanah Datar',
    level: 3,
    status: 'Level III (Siaga)',
    statusColor: '#ea580c',
    hazardRadiusKm: 4.5,
    rekomendasi: 'Masyarakat di sekitar G. Marapi dan pendaki tidak diperbolehkan memasuki dan melakukan kegiatan di dalam wilayah radius 4.5 km dari pusat erupsi (Kawah Verbeek).',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'ibu',
    nama: 'Gunung Ibu',
    kode: 'IBU',
    lat: 1.488,
    lng: 127.63,
    elevation: 1325,
    provinsi: 'Maluku Utara',
    kabupaten: 'Halmahera Barat',
    level: 3,
    status: 'Level III (Siaga)',
    statusColor: '#ea580c',
    hazardRadiusKm: 4.0,
    rekomendasi: 'Masyarakat di sekitar G. Ibu dan pengunjung tidak beraktivitas dalam radius 4 km dan perluasan sektoral berjarak 5 km ke arah bukaan kawah bagian utara.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },

  // ── Level II (Waspada) ──
  {
    id: 'anak-krakatau',
    nama: 'Gunung Anak Krakatau',
    kode: 'KRA',
    lat: -6.102,
    lng: 105.423,
    elevation: 157,
    provinsi: 'Lampung',
    kabupaten: 'Lampung Selatan',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 5.0,
    rekomendasi: 'Masyarakat/pengunjung/wisatawan tidak mendekati G. Anak Krakatau atau beraktivitas dalam radius 5 km dari kawah aktif.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'ili-lewotolok',
    nama: 'Gunung Ili Lewotolok',
    kode: 'LEW',
    lat: -8.272,
    lng: 123.505,
    elevation: 1423,
    provinsi: 'Nusa Tenggara Timur',
    kabupaten: 'Lembata',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 2.0,
    rekomendasi: 'Masyarakat di sekitar G. Ili Lewotolok maupun pengunjung/pendaki/wisatawan agar tidak memasuki dan tidak melakukan aktivitas di dalam wilayah radius 2 km dari pusat aktivitas.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'dukono',
    nama: 'Gunung Dukono',
    kode: 'DUK',
    lat: 1.693,
    lng: 127.894,
    elevation: 1229,
    provinsi: 'Maluku Utara',
    kabupaten: 'Halmahera Utara',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 3.0,
    rekomendasi: 'Masyarakat di sekitar G. Dukono dan pengunjung/wisatawan agar tidak beraktivitas, mendaki, dan mendekati Kawah Malupang Warirang di dalam radius 3 km.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'sinabung',
    nama: 'Gunung Sinabung',
    kode: 'SIN',
    lat: 3.17,
    lng: 98.392,
    elevation: 2460,
    provinsi: 'Sumatera Utara',
    kabupaten: 'Karo',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 3.0,
    rekomendasi: 'Masyarakat dan pengunjung agar tidak melakukan aktivitas pada desa-desa yang sudah direlokasi, serta lokasi di dalam radius radial 3 km dari puncak G. Sinabung.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'kerinci',
    nama: 'Gunung Kerinci',
    kode: 'KER',
    lat: -1.697,
    lng: 101.264,
    elevation: 3805,
    provinsi: 'Jambi & Sumatera Barat',
    kabupaten: 'Kerinci, Solok Selatan',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 3.0,
    rekomendasi: 'Masyarakat di sekitar G. Kerinci dan pengunjung/wisatawan tidak diperbolehkan mendaki kawah yang ada di puncak G. Kerinci di dalam radius 3 km dari kawah aktif.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'bromo',
    nama: 'Gunung Bromo',
    kode: 'BRO',
    lat: -7.942,
    lng: 112.95,
    elevation: 2329,
    provinsi: 'Jawa Timur',
    kabupaten: 'Probolinggo, Pasuruan, Malang',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 1.0,
    rekomendasi: 'Masyarakat di sekitar G. Bromo, pedagang, dan wisatawan agar tidak memasuki kawasan kawah dalam radius 1 km dari kawah aktif G. Bromo.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'raung',
    nama: 'Gunung Raung',
    kode: 'RAU',
    lat: -8.125,
    lng: 114.042,
    elevation: 3332,
    provinsi: 'Jawa Timur',
    kabupaten: 'Banyuwangi, Bondowoso, Jember',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 3.0,
    rekomendasi: 'Masyarakat dan pengunjung/wisatawan tidak mendekati pusat erupsi di kawah puncak dengan radius 3 km.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'karangetang',
    nama: 'Gunung Karangetang',
    kode: 'KGT',
    lat: 2.781,
    lng: 125.407,
    elevation: 1784,
    provinsi: 'Sulawesi Utara',
    kabupaten: 'Kepulauan Siau Tagulandang Biaro',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 2.5,
    rekomendasi: 'Masyarakat dan pengunjung/wisatawan tidak mendekati kawah utama dan kawah dua dalam radius 1.5 km serta sektoral 2.5 km ke arah barat daya dan selatan.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'ruang',
    nama: 'Gunung Ruang',
    kode: 'RUA',
    lat: 2.302,
    lng: 125.367,
    elevation: 725,
    provinsi: 'Sulawesi Utara',
    kabupaten: 'Kepulauan Sitaro',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 2.0,
    rekomendasi: 'Masyarakat di sekitar G. Ruang dan pengunjung agar tetap waspada dan tidak memasuki wilayah radius 2 km dari kawah aktif.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'lokon',
    nama: 'Gunung Lokon',
    kode: 'LOK',
    lat: 1.358,
    lng: 124.792,
    elevation: 1580,
    provinsi: 'Sulawesi Utara',
    kabupaten: 'Tomohon',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 1.5,
    rekomendasi: 'Masyarakat dan wisatawan agar tidak mendekati dan beraktivitas di dalam radius 1.5 km dari Kawah Tompaluan (pusat aktivitas).',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'soputan',
    nama: 'Gunung Soputan',
    kode: 'SOP',
    lat: 1.112,
    lng: 124.737,
    elevation: 1785,
    provinsi: 'Sulawesi Utara',
    kabupaten: 'Minahasa Tenggara',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 1.5,
    rekomendasi: 'Masyarakat agar tidak beraktivitas di dalam radius 1.5 km dari puncak G. Soputan dan sektoral barat-barat daya sejauh 2.5 km.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'awu',
    nama: 'Gunung Awu',
    kode: 'AWU',
    lat: 3.682,
    lng: 125.456,
    elevation: 1320,
    provinsi: 'Sulawesi Utara',
    kabupaten: 'Kepulauan Sangihe',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 3.0,
    rekomendasi: 'Masyarakat dan pengunjung tidak mendekati dan beraktivitas di dalam radius 3 km dari kawah puncak G. Awu.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'dempo',
    nama: 'Gunung Dempo',
    kode: 'DMP',
    lat: -4.03,
    lng: 103.13,
    elevation: 3173,
    provinsi: 'Sumatera Selatan',
    kabupaten: 'Pagar Alam',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 1.0,
    rekomendasi: 'Masyarakat, pengunjung/wisatawan tidak diperbolehkan mendekati dan bermalam di pusat aktivitas kawah dalam radius 1 km.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'rinjani',
    nama: 'Gunung Rinjani',
    kode: 'RIN',
    lat: -8.411,
    lng: 116.457,
    elevation: 3726,
    provinsi: 'Nusa Tenggara Barat',
    kabupaten: 'Lombok Utara, Lombok Timur',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 1.5,
    rekomendasi: 'Masyarakat di sekitar G. Rinjani dan pendaki tidak melakukan aktivitas di dalam Kaldera Rinjani dalam radius 1.5 km dari kawah Barujari.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'gamalama',
    nama: 'Gunung Gamalama',
    kode: 'GML',
    lat: 0.8,
    lng: 127.325,
    elevation: 1715,
    provinsi: 'Maluku Utara',
    kabupaten: 'Kota Ternate',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 1.5,
    rekomendasi: 'Masyarakat di sekitar G. Gamalama dan pengunjung agar tidak beraktivitas di dalam radius 1.5 km dari kawah utama di puncak.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'dieng',
    nama: 'Gunung Dieng',
    kode: 'DIE',
    lat: -7.2,
    lng: 109.9,
    elevation: 2565,
    provinsi: 'Jawa Tengah',
    kabupaten: 'Banjarnegara, Wonosobo, Batang',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 1.0,
    rekomendasi: 'Masyarakat dan wisatawan agar tidak mendekati Kawah Sileri pada jarak 1 km dari bibir kawah dan tidak mendekati Kawah Timbang pada jarak 500 meter.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },

  // ── Level I (Normal) Key Reference Volcanoes ──
  {
    id: 'agung',
    nama: 'Gunung Agung',
    kode: 'AGU',
    lat: -8.343,
    lng: 115.508,
    elevation: 3142,
    provinsi: 'Bali',
    kabupaten: 'Karangasem',
    level: 1,
    status: 'Level I (Normal)',
    statusColor: '#10b981',
    hazardRadiusKm: 0,
    rekomendasi: 'Masyarakat dan pendaki/wisatawan tetap berhati-hati dan mematuhi batas pendakian yang direkomendasikan PVMBG.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'batur',
    nama: 'Gunung Batur',
    kode: 'BAT',
    lat: -8.242,
    lng: 115.375,
    elevation: 1717,
    provinsi: 'Bali',
    kabupaten: 'Bangli',
    level: 1,
    status: 'Level I (Normal)',
    statusColor: '#10b981',
    hazardRadiusKm: 0,
    rekomendasi: 'Aktivitas vulkanik dalam batas normal. Pendakian dapat dilakukan dengan memperhatikan petunjuk pemandu.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'tangkuban-parahu',
    nama: 'Gunung Tangkuban Parahu',
    kode: 'TPR',
    lat: -6.77,
    lng: 107.6,
    elevation: 2084,
    provinsi: 'Jawa Barat',
    kabupaten: 'Subang, Bandung Barat',
    level: 1,
    status: 'Level I (Normal)',
    statusColor: '#10b981',
    hazardRadiusKm: 0,
    rekomendasi: 'Masyarakat tidak turun ke dasar kawah aktif dan tidak mendekati lubang hembusan gas beracun.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'gede',
    nama: 'Gunung Gede',
    kode: 'GED',
    lat: -6.78,
    lng: 106.98,
    elevation: 2958,
    provinsi: 'Jawa Barat',
    kabupaten: 'Cianjur, Sukabumi, Bogor',
    level: 1,
    status: 'Level I (Normal)',
    statusColor: '#10b981',
    hazardRadiusKm: 0,
    rekomendasi: 'Status Normal. Patuhi aturan Taman Nasional Gunung Gede Pangrango.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'slamet',
    nama: 'Gunung Slamet',
    kode: 'SLA',
    lat: -7.242,
    lng: 109.208,
    elevation: 3432,
    provinsi: 'Jawa Tengah',
    kabupaten: 'Pemalang, Banyumas, Brebes, Tegal, Purbalingga',
    level: 1,
    status: 'Level I (Normal)',
    statusColor: '#10b981',
    hazardRadiusKm: 0,
    rekomendasi: 'Masyarakat dan wisatawan agar tidak beraktivitas dalam radius 2 km dari kawah puncak.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'kelimutu',
    nama: 'Gunung Kelimutu',
    kode: 'KLM',
    lat: -8.77,
    lng: 121.82,
    elevation: 1639,
    provinsi: 'Nusa Tenggara Timur',
    kabupaten: 'Ende',
    level: 1,
    status: 'Level I (Normal)',
    statusColor: '#10b981',
    hazardRadiusKm: 0,
    rekomendasi: 'Status Normal. Wisatawan agar tidak melompati pagar pembatas danau kawah.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'tambora',
    nama: 'Gunung Tambora',
    kode: 'TAM',
    lat: -8.25,
    lng: 118.0,
    elevation: 2851,
    provinsi: 'Nusa Tenggara Barat',
    kabupaten: 'Dompu, Bima',
    level: 1,
    status: 'Level I (Normal)',
    statusColor: '#10b981',
    hazardRadiusKm: 0,
    rekomendasi: 'Status Normal. Patuhi petunjuk pemandu Taman Nasional Gunung Tambora.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'sangeangapi',
    nama: 'Gunung Sangeangapi',
    kode: 'SAN',
    lat: -8.2,
    lng: 119.07,
    elevation: 1949,
    provinsi: 'Nusa Tenggara Barat',
    kabupaten: 'Bima',
    level: 2,
    status: 'Level II (Waspada)',
    statusColor: '#eab308',
    hazardRadiusKm: 1.5,
    rekomendasi: 'Masyarakat dan pengunjung agar tidak mendekati pusat kawah aktif dalam radius 1.5 km.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'kelud',
    nama: 'Gunung Kelud',
    kode: 'KLD',
    lat: -7.93,
    lng: 112.308,
    elevation: 1731,
    provinsi: 'Jawa Timur',
    kabupaten: 'Kediri, Blitar, Malang',
    level: 1,
    status: 'Level I (Normal)',
    statusColor: '#10b981',
    hazardRadiusKm: 0,
    rekomendasi: 'Status Normal. Masyarakat agar tetap waspada terhadap potensi lahar dingin di musim hujan.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  },
  {
    id: 'ijen',
    nama: 'Gunung Ijen',
    kode: 'IJN',
    lat: -8.058,
    lng: 114.242,
    elevation: 2386,
    provinsi: 'Jawa Timur',
    kabupaten: 'Banyuwangi, Bondowoso',
    level: 1,
    status: 'Level I (Normal)',
    statusColor: '#10b981',
    hazardRadiusKm: 0.5,
    rekomendasi: 'Masyarakat dan pengunjung/wisatawan agar tidak mendekati dasar kawah pada malam hari dan selalu menggunakan masker gas.',
    link: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
  }
]

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url)
    const minLevel = parseInt(searchParams.get('min_level') || '1', 10)

    // Attempt live check from MAGMA ESDM
    // If upstream times out or fails (due to ESDM TLS cipher resets), fallback immediately to authoritative catalog
    let volcanoes = [...MASTER_VOLCANOES]

    try {
      const magmaRes = await fetch('https://magma.esdm.go.id/v1/gunung-api/tingkat-aktivitas', {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
          'Accept': 'text/html,application/json',
        },
        signal: AbortSignal.timeout(3000), // quick 3s timeout
      }).catch(() => null)

      if (magmaRes && magmaRes.ok) {
        const text = await magmaRes.text()
        // If MAGMA returns HTML or JSON, update any level changes
        // E.g. check for volcano names and status badges
        volcanoes = volcanoes.map((v) => {
          if (text.includes(v.nama) || text.includes(v.kode)) {
            // Updated tag if found
            return { ...v, updatedAt: 'MAGMA ESDM Terkini' }
          }
          return v
        })
      }
    } catch {
      // Graceful fallback to verified catalog
    }

    // Filter by minLevel
    if (minLevel > 1) {
      volcanoes = volcanoes.filter((v) => v.level >= minLevel)
    }

    return NextResponse.json(
      {
        success: true,
        source: 'PVMBG - Badan Geologi Kementerian ESDM (MAGMA Indonesia)',
        sourceUrl: 'https://magma.esdm.go.id/v1/gunung-api/laporan',
        total: volcanoes.length,
        data: volcanoes,
      },
      {
        headers: {
          'Cache-Control': 'public, s-maxage=600, stale-while-revalidate=300',
        },
      }
    )
  } catch (error: any) {
    console.error('[API magma-gunung] Error:', error)
    return NextResponse.json(
      { success: false, message: error?.message || 'Internal Server Error' },
      { status: 500 }
    )
  }
}
